CREATE TABLE IF NOT EXISTS day_book(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    task TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT  '',
    performance TEXT NOT NULL DEFAULT  '',
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)
